version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./vhost.d:/etc/nginx/vhost.d:ro
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
      - DEFAULT_EMAIL=
    volumes:
      - certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  ghost:
    image: ghost
    restart: always
    expose:
      - "2368"
    environment:
      - url=https://web.jaimelaborda.es
      - VIRTUAL_HOST=web.jaimelaborda.es
      - LETSENCRYPT_HOST=web.jaimelaborda.es
    volumes:
      - ./ghost/content/:/var/lib/ghost/content/:rw

  nodered:
    image: nodered/node-red
    restart: always
    expose: 
      - "1880"
    environment:
      - VIRTUAL_HOST=nodered.jaimelaborda.es
      - LETSENCRYPT_HOST=nodered.jaimelaborda.es
    volumes:
      - node-red-data:/data

  mail:
    image: analogic/poste.io
    restart: always
    expose:
      - "80"
    ports: 
      - "25:25"
      - "110:110"
      - "143:143"
      - "587:587"
      - "993:993"
      - "995:995"
      - "4190:4190"
    environment:
      - HTTPS=OFF
      - DISABLE_CLAMAV=TRUE
      - DISABLE_RSPAMD=TRUE
      - VIRTUAL_HOST=mail.jaimelaborda.es
      - LETSENCRYPT_HOST=mail.jaimelaborda.es
    volumes:
      - mail-data:/data
 
volumes: 
  node-red-data:
  certs:
  html:
  mail-data:

